### ISSUE TITLE
gittio installs wrong version for Android

### ISSUE THREAD

**Issue by Topener** [FokkeZB/gittio#102]
When I try to install `Ti.Ga` it will install `Ti.GoogleAnalytics` for android, even though there is a `Ti.Ga` version for android.

**Comment by FokkeZB** [comment]
That's because there was a 1.1 version once, which is higher then the current 1.0.1:
http://gitt.io/component/ti.ga

Compare:
https://github.com/benbahrenburg/Ti.GA/tree/ed1601dcc6260dfe75ca617d12fe08f8e90d3184/Android/dist
https://github.com/benbahrenburg/Ti.GA/tree/master/Android/dist

I will delete the old versions but gitTio might re-index them.
